### ISSUE TITLE
Crashes on init if your appDelegate has no window property

### ISSUE THREAD

**Issue by efetepe** [cezarywojcik/CWStatusBarNotification#62]
self.notificationLabelBackgroundColor = [[UIApplication sharedApplication] delegate].window.tintColor;

makes my app crash, since we don't implement window in our delegate, since it's an optional property

**Comment by cezarywojcik** [comment]
This issue should be resolved in release `2.3.2`.

**Comment by efetepe** [comment]
It's still crashing:
```2015-08-27 13:21:10.692 QuizUp[4727:1441696] -[AppDelegate window]: unrecognized selector sent to instance 0x1740117d0
2015-08-27 13:21:10.700 QuizUp[4727:1441696] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AppDelegate window]: unrecognized selector sent to instance 0x1740117d0'```

It'd work with
`if (if ([[[UIApplication sharedApplication] delegate] respondsToSelector:@selector(window)]) {`

**Comment by cezarywojcik** [comment]
Oops, yeah, my bad. Did that for `2.3.3`. Let me know if that works for you.
